# Nombre de tu microservicio
spring.application.name=catering-calculation-service

# Puerto de escucha para Postman
server.port=8080

# Base de datos en memoria para pruebas rápidas en el Sprint 2
spring.datasource.url=jdbc:h2:mem:minutadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update