# Nombre del Microservicio
spring.application.name=identity-access-service

# Puerto de escucha único para Usuarios
server.port=8084

# Conexión a tu XAMPP de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/kaukaukids_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-className=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false