# Nombre del Microservicio
spring.application.name=pago-service

# Puerto de escucha único (para que conviva con evento en el 8082 y minuta en el 8081)
server.port=8083

# Conexión limpia a tu XAMPP de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/kaukaukids_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-className=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate JPA para MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactivar advertencia visual en consola
spring.jpa.open-in-view=false